In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

C:\Users\AlokVerma\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


In [3]:
df = pd.read_csv(r"C:\Users\AlokVerma\Desktop\BBD CSE AI ML\spam.csv")

In [4]:
df.head(5)

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df.Category.value_counts()/len(df)*100

Category
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [7]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [8]:
df.head(5)

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [9]:
new_df = pd.read_csv('spam.csv')

In [10]:
new_df['Category'].replace({'ham':0,'spam':1}, inplace=True)

C:\Users\AlokVerma\AppData\Local\Temp\ipykernel_18724\2701969205.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  new_df['Category'].replace({'ham':0,'spam':1}, inplace=True)


0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Category, Length: 5572, dtype: object

In [11]:
new_df.head(5)

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [12]:
df.head(5)

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [13]:
df.shape

(5572, 3)

#### **Train Test Split**

In [14]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam,test_size=0.2)

In [15]:
X_train.shape

(4457,)

In [16]:
X_test.shape

(1115,)

In [17]:
X_train[:4]

2066    Cos daddy arranging time c wat time fetch ü ma...
5141    FREE for 1st week! No1 Nokia tone 4 ur mobile ...
3442    Get a FREE mobile video player FREE movie. To ...
534                                       I'll be late...
Name: Message, dtype: str

In [18]:
y_train[:4]

2066    0
5141    1
3442    1
534     0
Name: spam, dtype: int64

#### **Create bag of words representation using CountVectorizer**

In [19]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_test_cv = v.transform(X_test)

In [20]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59475 stored elements and shape (4457, 7789)>

In [21]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
X_train_cv.shape

(4457, 7789)

In [23]:
v.get_feature_names_out()[1771]

'cheaper'

In [24]:
v.vocabulary_

{'cos': 2036,
 'daddy': 2164,
 'arranging': 1083,
 'time': 6948,
 'wat': 7445,
 'fetch': 2843,
 'mah': 4345,
 'free': 3014,
 'for': 2965,
 '1st': 342,
 'week': 7489,
 'no1': 4824,
 'nokia': 4832,
 'tone': 7008,
 'ur': 7249,
 'mobile': 4583,
 'every': 2687,
 'just': 3903,
 'txt': 7146,
 'to': 6979,
 '8077': 652,
 'get': 3149,
 'txting': 7151,
 'and': 970,
 'tell': 6802,
 'mates': 4415,
 'www': 7687,
 'getzed': 3158,
 'co': 1886,
 'uk': 7171,
 'pobox': 5301,
 '36504': 461,
 'w45wq': 7390,
 '16': 322,
 'norm150p': 4851,
 'video': 7336,
 'player': 5278,
 'movie': 4649,
 'collect': 1909,
 'text': 6836,
 'go': 3191,
 '89105': 712,
 'its': 3794,
 'extra': 2755,
 'films': 2870,
 'can': 1657,
 'be': 1292,
 'ordered': 5018,
 'apply': 1032,
 '18': 326,
 'yrs': 7768,
 'only': 4985,
 'll': 4187,
 'late': 4051,
 'came': 1653,
 'look': 4223,
 'at': 1129,
 'the': 6863,
 'flat': 2913,
 'seems': 6035,
 'ok': 4954,
 'in': 3666,
 'his': 3472,
 '50s': 554,
 'is': 3774,
 'away': 1185,
 'alot': 931,
 'wiv': 

In [25]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
np.where(X_train_np[0]!=0)

(array([1083, 2036, 2164, 2843, 4345, 6948, 7445]),)

#### **Naive Bayes Classifier**

In [27]:
model = MultinomialNB()
model.fit(X_train_cv, y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [28]:
y_pred = model.predict(X_test_cv)

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       968
           1       0.95      0.96      0.96       147

    accuracy                           0.99      1115
   macro avg       0.97      0.98      0.97      1115
weighted avg       0.99      0.99      0.99      1115



#### **Test on a random datapoint**

In [30]:
message = {"Upto 20% off on parking, exclusing offer just for you"}

In [31]:
message_cnt = v.transform(message)

model.predict(message_cnt)

array([1])