In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.1.3


In [4]:
l = [1,2,3,4]
print(type(l))
print(l)

<class 'list'>
[1, 2, 3, 4]


In [5]:
n = np.array([1,2,3,4])
print(type(n))
print(n)

<class 'numpy.ndarray'>
[1 2 3 4]


In [7]:
n = np.array([[1,2,3],[11,22,33],[77,65,44]])
print(type(n))
print(n)

<class 'numpy.ndarray'>
[[ 1  2  3]
 [11 22 33]
 [77 65 44]]


In [8]:
n.shape

(3, 3)

In [11]:
n = np.array([[11,22,33],[77,65,44]])
print(type(n))
print(n)

<class 'numpy.ndarray'>
[[11 22 33]
 [77 65 44]]


In [12]:
n.shape

(2, 3)

In [13]:
print(n[2])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [14]:
n = np.array([1,2,3,4])
print(type(n))
print(n)

<class 'numpy.ndarray'>
[1 2 3 4]


In [16]:
n[0] =2000

In [17]:
print(n)

[2000    2    3    4]


In [18]:
print(type(n))

<class 'numpy.ndarray'>


In [19]:
n[:2]

array([2000,    2])

In [20]:
print(n[:10])

[2000    2    3    4]


In [21]:
print(n[3:10])

[4]


In [23]:
n.shape

(4,)

In [24]:
n.size

4

In [25]:
n.dtype

dtype('int64')

In [27]:
n.reshape(2,2)

array([[2000,    2],
       [   3,    4]])